
import {initializeApp} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged,createUserWithEmailAndPassword} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc,updateDoc,deleteDoc,collection,getDocs,addDoc,serverTimestamp,writeBatch} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDOKqDlPrdoXAGF6UoWm8bz3L9DEmIhD5E",authDomain:"vantage-journal.firebaseapp.com",projectId:"vantage-journal",storageBucket:"vantage-journal.firebasestorage.app",messagingSenderId:"823515562113",appId:"1:823515562113:web:698399e453fa55e9984d80"};
const OWNER_UID="p9MriJysILMUdqWVl844PTF0xgo2", EID="main";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
const icons={Explore:"🧭",Journal:"▣",Items:"🎒",Discoveries:"✣",Members:"👥",Activity:"♙",Guide:"?"};
const pages=["Explore","Journal","Items","Discoveries","Members","Activity","Guide"];
let page="Explore",detail=null,member=null,state={locations:{},discoveries:[],members:{},current:null};

$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch{$("loginError").textContent="Sign-in failed. Check your email and password."}};
$("signOutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$("authScreen").classList.remove("hidden");return}try{await bootstrap(user);member=await memberFor(user.uid);if(!member)throw Error("This account is not a member of the expedition.");$("profileName").textContent=member.displayName;$("profileRole").textContent=member.role==="owner"?"Owner":"Member";$("profileInitial").textContent=member.displayName[0];$("authScreen").classList.add("hidden");await load();render()}catch(e){$("loginError").textContent=e.message;await signOut(auth)}});
async function bootstrap(u){if(u.uid!==OWNER_UID)return;let e=doc(db,"expeditions",EID),m=doc(db,"expeditions",EID,"members",u.uid);if(!(await getDoc(e)).exists())await setDoc(e,{name:"Vantage Expedition",ownerId:OWNER_UID,createdAt:serverTimestamp()});if(!(await getDoc(m)).exists())await setDoc(m,{displayName:"Pete",role:"owner",joinedAt:serverTimestamp()})}
async function memberFor(uid){let s=await getDoc(doc(db,"expeditions",EID,"members",uid));return s.exists()?s.data():null}
async function load(){state={locations:{},discoveries:[],members:{},current:null};(await getDocs(collection(db,"expeditions",EID,"locations"))).forEach(s=>state.locations[s.id]={id:s.id,...s.data()});(await getDocs(collection(db,"expeditions",EID,"discoveries"))).forEach(s=>state.discoveries.push({id:s.id,...s.data()}));(await getDocs(collection(db,"expeditions",EID,"members"))).forEach(s=>state.members[s.id]={uid:s.id,...s.data()});let e=await getDoc(doc(db,"expeditions",EID));state.current=e.data()?.currentLocation||null;$("memberCount").textContent=`👥 Vantage Expedition · ${Object.keys(state.members).length} member${Object.keys(state.members).length===1?"":"s"}`}
function nav(m=false){return pages.slice(0,m?4:7).map(p=>`<button class="navbtn ${page===p?"active":""}" data-page="${p}">${m?`<span>${icons[p]}</span>`:icons[p]+" &nbsp;"}${p}</button>`).join("")}
function tag(t=""){if(t.includes("Requirement"))return'<span class="tag req">Requirement</span>';if(t.includes("Item"))return'<span class="tag">Item</span>';if(t.includes("Nothing"))return'<span class="tag locked">No result</span>';return'<span class="tag note">Note</span>'}
function drow(d){return`<div class="row"><div class="row-icon">${d.type?.includes("Item")?"🎒":d.type?.includes("Requirement")?"🔑":"📝"}</div><div class="row-main"><strong>${d.title||d.type}</strong><small>${(d.action||"").toUpperCase()}${d.specific?" → "+d.specific:""}${d.notes?" · "+d.notes:""}</small><small>${d.byName||"Member"} · ${d.dateText||""}</small></div>${tag(d.type)}</div>`}
function explore(){if(!state.current)return`<div class="card empty"><h2>Start your shared journal</h2><p>Add the first location when you begin playing.</p><button class="primary" id="newLocation">+ Add first location</button></div>`;let l=state.locations[state.current]||{},ds=state.discoveries.filter(d=>d.location==state.current);return`<div class="grid2"><div class="card"><div class="meta">CURRENT LOCATION</div><div class="location-number">${state.current}</div><div class="location-name">${l.name||"Unnamed location"}</div><p>${l.contents||l.notes||"No location notes yet."}</p><div class="pillbar">${l.return?'<span class="pill">⭐ Return here</span>':""}${l.tags?.map(x=>`<span class="pill">${x}</span>`).join("")||""}</div><div style="margin-top:16px"><button class="secondary" id="editCurrent">Edit location</button></div></div><div class="card"><h3>Quick record</h3><div class="quick">${[["👁","Look"],["🤝","Help"],["💬","Engage"],["✋","Take"],["⚔","Overpower"],["🧭","Move"]].map(x=>`<button class="action" data-action="${x[1]}"><span>${x[0]}</span>${x[1]}</button>`).join("")}</div><button class="primary wide" id="addDiscovery" style="margin-top:10px">+ Add discovery</button></div></div><h2 class="section-title">What we know here</h2><div class="card knowledge">${ds.length?ds.map(drow).join(""):'<div class="empty">Nothing recorded here yet.</div>'}</div>`}
function journal(){let es=Object.entries(state.locations).sort((a,b)=>+a[0]-+b[0]);return`<div class="toolbar"><input id="searchJournal" class="search" placeholder="🔎 Search locations, items and notes..."><button class="primary" id="newLocation">+ Location</button></div><div class="card knowledge">${es.length?es.map(([n,l])=>{let ds=state.discoveries.filter(d=>d.location==n);return`<div class="row clickable journal-entry" data-id="${n}"><div class="row-main"><strong>${n} &nbsp; ${l.name||"Unnamed location"}</strong><small>${l.contents||l.notes||ds.map(x=>x.title).filter(Boolean).join(" · ")||"No notes"}</small><small>${ds.length} discover${ds.length===1?"y":"ies"}</small></div>${l.return?'<span class="star">★</span>':""}</div>`}).join(""):'<div class="empty">No locations yet.</div>'}</div>`}
function locationView(n){let l=state.locations[n],ds=state.discoveries.filter(d=>d.location==n);return`<button class="secondary" id="back">← Journal</button><div class="split" style="margin-top:12px"><div class="card"><div class="meta">LOCATION</div><h2>${n} · ${l.name||"Unnamed location"} ${l.return?'<span class="star">★</span>':""}</h2><h3>What's here</h3><p>${l.contents||"Nothing recorded yet."}</p><h3>General notes</h3><p>${l.notes||"No notes."}</p><button class="secondary" id="editLocation">Edit location</button></div><div class="card"><h2>Discoveries</h2><div class="knowledge">${ds.length?ds.map(drow).join(""):'<div class="empty">No discoveries yet.</div>'}</div><button class="primary wide" id="addDiscovery" style="margin-top:12px">+ Add discovery</button></div></div>`}
function items(){let map={};state.discoveries.filter(d=>d.type?.includes("Item")&&d.title).forEach(d=>(map[d.title]??=[]).push(d));return`<div class="toolbar"><input id="itemSearch" class="search" placeholder="🔎 Find a discovered item..."></div><div class="card knowledge">${Object.keys(map).length?Object.entries(map).sort().map(([name,ds])=>`<div class="row clickable item-entry" data-item="${encodeURIComponent(name)}"><div class="row-icon">🎒</div><div class="row-main"><strong>${name}</strong><small>${ds.length} known source${ds.length===1?"":"s"}</small>${ds.slice(0,2).map(d=>`<small>📍 ${d.location} · ${(d.action||"").toUpperCase()}${d.specific?" → "+d.specific:""}</small>`).join("")}</div></div>`).join(""):'<div class="empty">Items appear only after you or Min discover them.</div>'}</div>`}
function itemView(name){let ds=state.discoveries.filter(d=>d.type?.includes("Item")&&d.title===name);let effect=ds.find(d=>d.itemEffect)?.itemEffect||"No effect text recorded yet.";return`<button class="secondary" id="backItems">← Items</button><div class="card" style="margin-top:12px"><div class="meta">DISCOVERED ITEM</div><h2>🎒 ${name}</h2><p><strong>What it does:</strong> ${effect}</p><h3>Known sources</h3>${ds.map(d=>`<div class="item-source"><strong>Location ${d.location}</strong> · ${(d.action||"").toUpperCase()}${d.specific?" → "+d.specific:""}<br><span class="meta">${d.notes||""} · recorded by ${d.byName}</span></div>`).join("")}</div>`}
function discoveries(){return`<div class="toolbar"><input id="discSearch" class="search" placeholder="🔎 Search all discoveries..."></div><div class="card knowledge">${state.discoveries.length?state.discoveries.map(drow).join(""):'<div class="empty">No discoveries yet.</div>'}</div>`}
function members(){let own=member?.role==="owner";return`<div class="card"><h2>Expedition members</h2><p class="meta">Shared journal access. Only the Owner can manage membership.</p><div class="knowledge">${Object.values(state.members).map(m=>`<div class="row"><div class="avatar">${m.displayName[0]}</div><div class="row-main"><strong>${m.displayName}</strong><small>${m.role==="owner"?"Owner / Admin":"Member"}</small></div></div>`).join("")}</div>${own?`<div style="margin-top:16px"><button class="primary" id="addExistingMember">+ Add Min</button><p class="owner-only">First create Min's account in Firebase Authentication. Then use her User UID here.</p></div>`:""}</div>`}
function activity(){return`<div class="card knowledge">${state.discoveries.length?[...state.discoveries].reverse().map(d=>`<div class="row"><div class="avatar">${(d.byName||"M")[0]}</div><div class="row-main"><strong>${d.byName||"Member"} recorded ${d.title||d.type}</strong><small>Location ${d.location} · ${(d.action||"").toUpperCase()}${d.specific?" → "+d.specific:""}</small><small>${d.dateText||""}</small></div></div>`).join(""):'<div class="empty">No activity yet.</div>'}</div>`}
function guide(){return`<div class="card"><h2>Journal principles</h2><p><strong>Spoiler-safe:</strong> items and locations only appear after you record them.</p><p><strong>Multiple item sources:</strong> finding the same item somewhere else adds another source rather than replacing the existing one.</p><p><strong>Shared knowledge:</strong> Pete and Min see the same locations, discoveries and item sources.</p></div>`}
function render(){ $("desktopNav").innerHTML=nav();$("mobileNav").innerHTML=nav(true);document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>{page=b.dataset.page;detail=null;render()});let title={Explore:["Explore","Record discoveries as you play"],Journal:["Journal","Persistent location knowledge"],Items:["Items","Where your discovered items can be found"],Discoveries:["Discoveries","Everything your expedition has learned"],Members:["Members","Shared expedition access"],Activity:["Activity","Recent journal additions"],Guide:["Guide","How the journal works"]}[page];$("pageTitle").textContent=title[0];$("pageSubtitle").textContent=title[1];$("content").innerHTML=detail?.kind==="location"?locationView(detail.id):detail?.kind==="item"?itemView(detail.id):({Explore:explore,Journal:journal,Items:items,Discoveries:discoveries,Members:members,Activity:activity,Guide:guide}[page]());
 document.querySelectorAll(".action").forEach(b=>b.onclick=()=>openDiscovery(b.dataset.action));document.querySelectorAll("#addDiscovery").forEach(b=>b.onclick=()=>openDiscovery());document.querySelectorAll("#newLocation").forEach(b=>b.onclick=()=>openLocation());$("editCurrent")&&($("editCurrent").onclick=()=>openLocation(state.current));$("editLocation")&&($("editLocation").onclick=()=>openLocation(detail.id));$("back")&&($("back").onclick=()=>{detail=null;render()});$("backItems")&&($("backItems").onclick=()=>{detail=null;render()});document.querySelectorAll(".journal-entry").forEach(r=>r.onclick=()=>{detail={kind:"location",id:r.dataset.id};render()});document.querySelectorAll(".item-entry").forEach(r=>r.onclick=()=>{detail={kind:"item",id:decodeURIComponent(r.dataset.item)};render()});$("addExistingMember")&&($("addExistingMember").onclick=openMember);
 [["searchJournal",".journal-entry"],["itemSearch",".item-entry"]].forEach(([id,sel])=>{$(id)&&($(id).oninput=()=>{let q=$(id).value.toLowerCase();document.querySelectorAll(sel).forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?"":"none")})});
}
function modal(html){$("modalContent").innerHTML=html;$("modalBackdrop").classList.remove("hidden")}function close(){ $("modalBackdrop").classList.add("hidden")}$("closeModal").onclick=close;
function openLocation(id=null){let l=id?state.locations[id]:{};modal(`<h2>${id?"Edit":"Add"} location</h2><div class="form-grid"><label class="field">Location number<input id="fLoc" type="number" value="${id||""}" ${id?"disabled":""}></label><label class="field">Name / short description<input id="fName" value="${l.name||""}" placeholder="Optional"></label><label class="field full">What's at this location?<textarea id="fContents" rows="3" placeholder="Structures, characters, notable features...">${l.contents||""}</textarea></label><label class="field full">General notes<textarea id="fNotes" rows="3">${l.notes||""}</textarea></label><label class="check full"><input id="fReturn" type="checkbox" ${l.return?"checked":""}> Mark to return</label></div><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="saveLocation">Save</button></div>`);$("cancel").onclick=close;$("saveLocation").onclick=async()=>{let n=id||$("fLoc").value.trim();if(!n)return;await setDoc(doc(db,"expeditions",EID,"locations",String(n)),{name:$("fName").value.trim(),contents:$("fContents").value.trim(),notes:$("fNotes").value.trim(),return:$("fReturn").checked,updatedBy:auth.currentUser.uid,updatedAt:serverTimestamp()},{merge:true});if(!state.current)await setDoc(doc(db,"expeditions",EID),{currentLocation:String(n)},{merge:true});await load();close();render()}}
function openDiscovery(action="Look"){let loc=detail?.kind==="location"?detail.id:state.current;modal(`<h2>Add discovery</h2><div class="form-grid"><label class="field">Location<input id="dLoc" type="number" value="${loc||""}"></label><label class="field">Action<select id="dAction">${["Look","Help","Engage","Take","Overpower","Move"].map(x=>`<option ${x===action?"selected":""}>${x}</option>`).join("")}</select></label><label class="field">Specific action<input id="dSpecific" placeholder="e.g. Study"></label><label class="field">Result type<select id="dType"><option>Item obtained</option><option>Item available / seen</option><option>Requirement discovered</option><option>Information / clue</option><option>Location changed</option><option>Nothing useful</option><option>Other</option></select></label><label class="field full">Item / requirement / discovery<input id="dTitle" placeholder="e.g. Grappling Hook"></label><label class="field full">What does the item do? <span class="meta">(optional)</span><textarea id="dEffect" rows="2" placeholder="Enter the card effect after you discover it"></textarea></label><label class="field full">Notes<textarea id="dNotes" rows="3" placeholder="What happened? Requirements? Useful details?"></textarea></label></div><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="saveDiscovery">Save discovery</button></div>`);$("cancel").onclick=close;$("saveDiscovery").onclick=async()=>{let loc=$("dLoc").value.trim();if(!loc)return;if(!(await getDoc(doc(db,"expeditions",EID,"locations",loc))).exists())await setDoc(doc(db,"expeditions",EID,"locations",loc),{name:"",contents:"",notes:"",return:false,createdAt:serverTimestamp()});await addDoc(collection(db,"expeditions",EID,"discoveries"),{location:loc,action:$("dAction").value,specific:$("dSpecific").value.trim(),type:$("dType").value,title:$("dTitle").value.trim(),itemEffect:$("dEffect").value.trim(),notes:$("dNotes").value.trim(),byUid:auth.currentUser.uid,byName:member.displayName,dateText:new Date().toLocaleDateString("en-AU",{day:"2-digit",month:"2-digit",year:"2-digit"}),createdAt:serverTimestamp()});await load();close();render()}}
function openMember(){modal(`<h2>Add Min</h2><p>Create Min in <strong>Firebase Authentication → Users</strong> first, then paste Min's User UID below.</p><div class="form-grid"><label class="field full">Min's User UID<input id="mUid" placeholder="Firebase User UID"></label></div><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="saveMember">Add Min</button></div>`);$("cancel").onclick=close;$("saveMember").onclick=async()=>{let uid=$("mUid").value.trim();if(!uid)return;await setDoc(doc(db,"expeditions",EID,"members",uid),{displayName:"Min",role:"member",joinedAt:serverTimestamp(),addedBy:auth.currentUser.uid});await load();close();render()}}
render();
