
import {initializeApp} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged,createUserWithEmailAndPassword} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc,updateDoc,deleteDoc,collection,getDocs,addDoc,serverTimestamp,writeBatch} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDOKqDlPrdoXAGF6UoWm8bz3L9DEmIhD5E",authDomain:"vantage-journal.firebaseapp.com",projectId:"vantage-journal",storageBucket:"vantage-journal.firebasestorage.app",messagingSenderId:"823515562113",appId:"1:823515562113:web:698399e453fa55e9984d80"};
const OWNER_UID="p9MriJysILMUdqWVl844PTF0xgo2", EID="main";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
const icons={Explore:"🧭",Journal:"▣",Items:"🎒",Discoveries:"✣",Members:"👥",Activity:"♙",Guide:"?"};
const pages=["Explore","Journal","Items","Discoveries","Members","Activity","Guide"];
let page="Explore",detail=null,member=null,state={locations:{},discoveries:[],members:{},current:null};

$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch{$("loginError").textContent="Sign-in failed. Check your email and password."}};
$("signOutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$("authScreen").classList.remove("hidden");return}try{await bootstrap(user);member=await memberFor(user.uid);if(!member)throw Error("This account is not a member of the expedition.");$("profileName").textContent=member.displayName;$("profileRole").textContent=member.role==="owner"?"Owner":"Member";$("profileInitial").textContent=member.displayName[0];$("authScreen").classList.add("hidden");await load();render()}catch(e){$("loginError").textContent=e.message;await signOut(auth)}});
async function bootstrap(u){if(u.uid!==OWNER_UID)return;let e=doc(db,"expeditions",EID),m=doc(db,"expeditions",EID,"members",u.uid);if(!(await getDoc(e)).exists())await setDoc(e,{name:"Vantage Expedition",ownerId:OWNER_UID,createdAt:serverTimestamp()});if(!(await getDoc(m)).exists())await setDoc(m,{displayName:"Pete",role:"owner",joinedAt:serverTimestamp()})}
async function memberFor(uid){let s=await getDoc(doc(db,"expeditions",EID,"members",uid));return s.exists()?s.data():null}
async function load(){state={locations:{},discoveries:[],members:{},current:null};(await getDocs(collection(db,"expeditions",EID,"locations"))).forEach(s=>state.locations[s.id]={id:s.id,...s.data()});(await getDocs(collection(db,"expeditions",EID,"discoveries"))).forEach(s=>state.discoveries.push({id:s.id,...s.data()}));(await getDocs(collection(db,"expeditions",EID,"members"))).forEach(s=>state.members[s.id]={uid:s.id,...s.data()});let e=await getDoc(doc(db,"expeditions",EID));state.current=e.data()?.currentLocation||null;$("memberCount").textContent=`👥 Vantage Expedition · ${Object.keys(state.members).length} member${Object.keys(state.members).length===1?"":"s"}`}
function nav(m=false){return pages.slice(0,m?4:7).map(p=>`<button class="navbtn ${page===p?"active":""}" data-page="${p}">${m?`<span>${icons[p]}</span>`:icons[p]+" &nbsp;"}${p}</button>`).join("")}
function tag(t=""){if(t.includes("Requirement"))return'<span class="tag req">Requirement</span>';if(t.includes("Item"))return'<span class="tag">Item</span>';if(t.includes("Nothing"))return'<span class="tag locked">No result</span>';return'<span class="tag note">Note</span>'}
function moveLabel(v){if(!v)return "Blocked";if(v==="*")return "* · Storybook route";return `Location ${v}`}
function movementPanel(l){let m=l?.movement||{};let d=(dir,label,arrow)=>{let v=m[dir]||"";return `<div class="compass-dir"><span>${arrow} ${label}</span><strong>${moveLabel(v)}</strong>${v&&v!=="*"?`<button class="moveBtn" data-dest="${v}" data-dir="${dir}">Move here</button>`:""}</div>`};return `<div class="card movement-card"><div class="section-head"><div><div class="meta">MOVEMENT OPTIONS</div><h3>Compass</h3></div><button class="secondary" id="editMovement">Edit movement</button></div><div class="compass-grid"><div></div>${d("north","NORTH","↑")}<div></div>${d("west","WEST","←")}<div class="compass-center">✥</div>${d("east","EAST","→")}<div></div>${d("south","SOUTH","↓")}<div></div></div><div class="meta movement-help">Number = listed adjacent location · * = storybook route · blank = blocked</div></div>`}
function outcomeIcon(o){if(o.knowledge==="unknown")return"❓";if(o.rewardType==="Item")return"🎒";if(o.rewardType==="Money")return"💰";if(o.rewardType==="Resource")return"◆";if(o.rewardType==="Information")return"💡";return"✓"}
function outcomeText(o){if(o.knowledge==="unknown")return `${o.condition||"Other result"} → Unknown outcome`;let reward=o.rewardType==="Item"?`Item #${o.itemNumber||"?"}${o.itemName?" · "+o.itemName:""}`:o.rewardType==="Money"?`${o.value||""}`:o.value||o.rewardType||"Known outcome";return `${o.condition||"Known result"} → ${reward}${o.obtained?" · Obtained":""}`}
function drow(d){let outs=d.outcomes||[];if(!outs.length)return`<div class="row"><div class="row-icon">${d.type?.includes("Item")?"🎒":d.type?.includes("Requirement")?"🔑":"📝"}</div><div class="row-main"><strong>${d.title||d.type}</strong><small>${(d.action||"").toUpperCase()}${d.specific?" → "+d.specific:""}${d.notes?" · "+d.notes:""}</small><small>${d.byName||"Member"} · ${d.dateText||""}</small></div>${tag(d.type)}</div>`;
return`<div class="row"><div class="row-icon">🎲</div><div class="row-main"><strong>${(d.action||"Action").toUpperCase()}${d.specific?" → "+d.specific:""}</strong>${d.testDetails?`<small><b>Test:</b> ${d.testDetails}</small>`:""}${outs.map(o=>`<small>${outcomeIcon(o)} ${outcomeText(o)}</small>`).join("")}${d.notes?`<small>📝 ${d.notes}</small>`:""}<small>${d.byName||"Member"} · ${d.dateText||""}</small></div><span class="tag">${outs.length} outcome${outs.length===1?"":"s"}</span></div>`}
function explore(){if(!state.current)return`<div class="card empty"><h2>Start your shared journal</h2><p>Add the first location when you begin playing.</p><button class="primary" id="newLocation">+ Add first location</button></div>`;let l=state.locations[state.current]||{},ds=state.discoveries.filter(d=>d.location==state.current);return`<div class="grid2"><div class="card"><div class="meta">CURRENT LOCATION</div><div class="location-number">${state.current}</div><div class="location-name">${l.name||"Unnamed location"}</div><p>${l.contents||l.notes||"No location notes yet."}</p><div class="pillbar">${l.return?'<span class="pill">⭐ Return here</span>':""}${l.tags?.map(x=>`<span class="pill">${x}</span>`).join("")||""}</div><div style="margin-top:16px"><button class="secondary" id="editCurrent">Edit location</button></div></div><div class="card"><h3>Quick record</h3><div class="quick">${[["👁","Look"],["🤝","Help"],["💬","Engage"],["✋","Take"],["⚔","Overpower"],["🧭","Move"]].map(x=>`<button class="action" data-action="${x[1]}"><span>${x[0]}</span>${x[1]}</button>`).join("")}</div><button class="primary wide" id="addDiscovery" style="margin-top:10px">+ Add discovery</button></div></div><h2 class="section-title">What we know here</h2><div class="card knowledge">${ds.length?ds.map(drow).join(""):'<div class="empty">Nothing recorded here yet.</div>'}</div>`}
function journal(){let es=Object.entries(state.locations).sort((a,b)=>+a[0]-+b[0]);return`<div class="toolbar"><input id="searchJournal" class="search" placeholder="🔎 Search locations, items and notes..."><button class="primary" id="newLocation">+ Location</button></div><div class="card knowledge">${es.length?es.map(([n,l])=>{let ds=state.discoveries.filter(d=>d.location==n);return`<div class="row clickable journal-entry" data-id="${n}"><div class="row-main"><strong>${n} &nbsp; ${l.name||"Unnamed location"}</strong><small>${l.contents||l.notes||ds.map(x=>x.title).filter(Boolean).join(" · ")||"No notes"}</small><small>${ds.length} discover${ds.length===1?"y":"ies"}</small></div>${l.return?'<span class="star">★</span>':""}</div>`}).join(""):'<div class="empty">No locations yet.</div>'}</div>`}
function locationView(n){let l=state.locations[n],ds=state.discoveries.filter(d=>d.location==n);return`<button class="secondary" id="back">← Journal</button><div class="split" style="margin-top:12px"><div class="card"><div class="meta">LOCATION</div><h2>${n} · ${l.name||"Unnamed location"} ${l.return?'<span class="star">★</span>':""}</h2><h3>What's here</h3><p>${l.contents||"Nothing recorded yet."}</p><h3>General notes</h3><p>${l.notes||"No notes."}</p><button class="secondary" id="editLocation">Edit location</button></div><div class="card"><h2>Discoveries</h2><div class="knowledge">${ds.length?ds.map(drow).join(""):'<div class="empty">No discoveries yet.</div>'}</div><button class="primary wide" id="addDiscovery" style="margin-top:12px">+ Add discovery</button></div></div>${movementPanel(l)}`}
function knownItemSources(){
 let map={};
 state.discoveries.forEach(d=>{
   if(Array.isArray(d.outcomes)){
     d.outcomes.filter(o=>o.knowledge==="known"&&o.rewardType==="Item"&&o.itemNumber).forEach(o=>{
       let key=o.itemNumber, name=o.itemName||`Item #${key}`;
       (map[key]??={number:key,name,sources:[]}).sources.push({d,o});
     });
   }else if(d.type?.includes("Item")&&d.title){
     let key=d.cardNumber||d.title;(map[key]??={number:d.cardNumber||"",name:d.title,sources:[]}).sources.push({d,o:{knowledge:"known",rewardType:"Item",obtained:true}});
   }
 });return map
}
function items(){let map=knownItemSources();return`<div class="toolbar"><input id="itemSearch" class="search" placeholder="🔎 Find a discovered item or card number..."></div><div class="card knowledge">${Object.keys(map).length?Object.values(map).sort((a,b)=>String(a.number).localeCompare(String(b.number),undefined,{numeric:true})).map(it=>`<div class="row clickable item-entry" data-item="${encodeURIComponent(it.number||it.name)}"><div class="row-icon">🎒</div><div class="row-main"><strong>${it.number?`#${it.number} · `:""}${it.name}</strong><small>${it.sources.length} known source${it.sources.length===1?"":"s"}</small>${it.sources.slice(0,2).map(x=>`<small>📍 ${x.d.location} · ${(x.d.action||"").toUpperCase()}${x.d.specific?" → "+x.d.specific:""}</small>`).join("")}</div></div>`).join(""):'<div class="empty">Items appear only after the game reveals them to you.</div>'}</div>`}
function itemView(key){let it=knownItemSources()[key];if(!it)return`<div class="card">Item not found.</div>`;return`<button class="secondary" id="backItems">← Items</button><div class="card" style="margin-top:12px"><div class="meta">DISCOVERED ITEM</div><h2>🎒 ${it.number?`#${it.number} · `:""}${it.name}</h2><h3>Known sources</h3>${it.sources.map(x=>`<div class="item-source"><strong>Location ${x.d.location}</strong> · ${(x.d.action||"").toUpperCase()}${x.d.specific?" → "+x.d.specific:""}<br><span class="meta">${x.o.condition?x.o.condition+" · ":""}${x.o.obtained?"Obtained":"Known"}${x.d.notes?" · "+x.d.notes:""}</span></div>`).join("")}</div>`}
function discoveries(){return`<div class="toolbar"><input id="discSearch" class="search" placeholder="🔎 Search all discoveries..."></div><div class="card knowledge">${state.discoveries.length?state.discoveries.map(drow).join(""):'<div class="empty">No discoveries yet.</div>'}</div>`}
function members(){let own=member?.role==="owner";return`<div class="card"><h2>Expedition members</h2><p class="meta">Shared journal access. Only the Owner can manage membership.</p><div class="knowledge">${Object.values(state.members).map(m=>`<div class="row"><div class="avatar">${m.displayName[0]}</div><div class="row-main"><strong>${m.displayName}</strong><small>${m.role==="owner"?"Owner / Admin":"Member"}</small></div></div>`).join("")}</div>${own?`<div style="margin-top:16px"><button class="primary" id="addExistingMember">+ Add Min</button><p class="owner-only">First create Min's account in Firebase Authentication. Then use her User UID here.</p></div>`:""}</div>`}
function activity(){return`<div class="card knowledge">${state.discoveries.length?[...state.discoveries].reverse().map(d=>`<div class="row"><div class="avatar">${(d.byName||"M")[0]}</div><div class="row-main"><strong>${d.byName||"Member"} recorded ${d.title||d.type}</strong><small>Location ${d.location} · ${(d.action||"").toUpperCase()}${d.specific?" → "+d.specific:""}</small><small>${d.dateText||""}</small></div></div>`).join(""):'<div class="empty">No activity yet.</div>'}</div>`}
function guide(){return`<div class="card"><h2>Journal principles</h2><p><strong>Spoiler-safe:</strong> items and locations only appear after you record them.</p><p><strong>Multiple item sources:</strong> finding the same item somewhere else adds another source rather than replacing the existing one.</p><p><strong>Shared knowledge:</strong> Pete and Min see the same locations, discoveries and item sources.</p></div>`}
function render(){ $("desktopNav").innerHTML=nav();$("mobileNav").innerHTML=nav(true);document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>{page=b.dataset.page;detail=null;render()});let title={Explore:["Explore","Record discoveries as you play"],Journal:["Journal","Persistent location knowledge"],Items:["Items","Where your discovered items can be found"],Discoveries:["Discoveries","Everything your expedition has learned"],Members:["Members","Shared expedition access"],Activity:["Activity","Recent journal additions"],Guide:["Guide","How the journal works"]}[page];$("pageTitle").textContent=title[0];$("pageSubtitle").textContent=title[1];$("content").innerHTML=detail?.kind==="location"?locationView(detail.id):detail?.kind==="item"?itemView(detail.id):({Explore:explore,Journal:journal,Items:items,Discoveries:discoveries,Members:members,Activity:activity,Guide:guide}[page]());
 document.querySelectorAll(".action").forEach(b=>b.onclick=()=>openDiscovery(b.dataset.action));document.querySelectorAll("#addDiscovery").forEach(b=>b.onclick=()=>openDiscovery());document.querySelectorAll("#newLocation").forEach(b=>b.onclick=()=>openLocation());$("editCurrent")&&($("editCurrent").onclick=()=>openLocation(state.current));$("editLocation")&&($("editLocation").onclick=()=>openLocation(detail.id));$("back")&&($("back").onclick=()=>{detail=null;render()});$("backItems")&&($("backItems").onclick=()=>{detail=null;render()});document.querySelectorAll(".journal-entry").forEach(r=>r.onclick=()=>{detail={kind:"location",id:r.dataset.id};render()});document.querySelectorAll(".item-entry").forEach(r=>r.onclick=()=>{detail={kind:"item",id:decodeURIComponent(r.dataset.item)};render()});$("addExistingMember")&&($("addExistingMember").onclick=openMember);$("editMovement")&&($("editMovement").onclick=()=>openLocation(detail.id));document.querySelectorAll(".moveBtn").forEach(b=>b.onclick=()=>moveTo(b.dataset.dest,b.dataset.dir));
 [["searchJournal",".journal-entry"],["itemSearch",".item-entry"]].forEach(([id,sel])=>{$(id)&&($(id).oninput=()=>{let q=$(id).value.toLowerCase();document.querySelectorAll(sel).forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?"":"none")})});
}
function modal(html){$("modalContent").innerHTML=html;$("modalBackdrop").classList.remove("hidden")}function close(){ $("modalBackdrop").classList.add("hidden")}$("closeModal").onclick=close;
function openLocation(id=null){let l=id?state.locations[id]:{};modal(`<h2>${id?"Edit":"Add"} location</h2><div class="form-grid"><label class="field">Location number<input id="fLoc" type="number" value="${id||""}" ${id?"disabled":""}></label><label class="field">Name / short description<input id="fName" value="${l.name||""}" placeholder="Optional"></label><label class="field full">What's at this location?<textarea id="fContents" rows="3">${l.contents||""}</textarea></label><label class="field full">General notes<textarea id="fNotes" rows="3">${l.notes||""}</textarea></label></div><div class="movement-entry"><div class="meta">COMPASS / DEPART OPTIONS</div><p class="meta">Copy the four positions from the location card. Enter a location number, * for an unlisted/storybook route, or leave blank if blocked.</p><div class="quick-compass"><label class="field qnorth">↑ North<input id="mNorth" value="${l.movement?.north||""}" placeholder="number / *"></label><label class="field qwest">← West<input id="mWest" value="${l.movement?.west||""}" placeholder="number / *"></label><div class="qcenter">✥</div><label class="field qeast">East →<input id="mEast" value="${l.movement?.east||""}" placeholder="number / *"></label><label class="field qsouth">↓ South<input id="mSouth" value="${l.movement?.south||""}" placeholder="number / *"></label></div></div><label class="check"><input id="fReturn" type="checkbox" ${l.return?"checked":""}> Mark to return</label><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="saveLocation">Save</button></div>`);$("cancel").onclick=close;$("saveLocation").onclick=async()=>{let n=id||$("fLoc").value.trim();if(!n)return;const cm=v=>{v=v.trim();return v==="*"?"*":(/^\d+$/.test(v)?v:"")};let btn=$("saveLocation");btn.disabled=true;try{await setDoc(doc(db,"expeditions",EID,"locations",String(n)),{name:$("fName").value.trim(),contents:$("fContents").value.trim(),notes:$("fNotes").value.trim(),return:$("fReturn").checked,movement:{north:cm($("mNorth").value),east:cm($("mEast").value),south:cm($("mSouth").value),west:cm($("mWest").value)},updatedBy:auth.currentUser.uid,updatedAt:serverTimestamp()},{merge:true});if(!state.current)await updateDoc(doc(db,"expeditions",EID),{currentLocation:String(n)});close();await load();detail={kind:"location",id:String(n)};render()}catch(err){alert("Could not save: "+err.message);btn.disabled=false}}}
async function moveTo(dest,dir){try{let r=doc(db,"expeditions",EID,"locations",String(dest));if(!(await getDoc(r)).exists())await setDoc(r,{name:"",contents:"",notes:"",return:false,movement:{north:"",east:"",south:"",west:""},createdAt:serverTimestamp()});await updateDoc(doc(db,"expeditions",EID),{currentLocation:String(dest)});await addDoc(collection(db,"expeditions",EID,"activity"),{type:"movement",from:state.current||"",to:String(dest),direction:dir,byUid:auth.currentUser.uid,byName:member.displayName,dateText:new Date().toLocaleDateString("en-AU"),createdAt:serverTimestamp()});await load();detail={kind:"location",id:String(dest)};render()}catch(err){alert("Could not move: "+err.message)}}
function outcomeBlock(i){
 return `<div class="outcome-box" data-outcome="${i}">
  <div class="outcome-head"><strong>Outcome ${i+1}</strong>${i?`<button type="button" class="removeOutcome" data-i="${i}">Remove</button>`:""}</div>
  <label class="field full">Result / condition <span class="meta">(only what the game has revealed)</span><input class="oCondition" placeholder="e.g. 3+ successes, specific symbol, other result"></label>
  <label class="field">Knowledge<select class="oKnowledge"><option value="known">Known outcome</option><option value="unknown">Unknown outcome</option></select></label>
  <label class="field rewardField">Reward type<select class="oType"><option>Item</option><option>Money</option><option>Resource</option><option>Information</option><option>Effect</option><option>Other</option></select></label>
  <label class="field itemNumberField">Item/card number<input class="oNumber" placeholder="e.g. 1164"></label>
  <label class="field itemNameField">Item name <span class="meta">(if revealed)</span><input class="oName" placeholder="Optional"></label>
  <label class="field valueField hidden">Outcome / amount<input class="oValue" placeholder="e.g. $4"></label>
  <label class="check full obtainedField"><input class="oObtained" type="checkbox"> We actually obtained this outcome</label>
 </div>`
}
function wireOutcomeBoxes(){
 document.querySelectorAll(".outcome-box").forEach(box=>{
   const know=box.querySelector(".oKnowledge"),typ=box.querySelector(".oType");
   function refresh(){
     let unknown=know.value==="unknown", item=typ.value==="Item";
     box.querySelector(".rewardField").classList.toggle("hidden",unknown);
     box.querySelector(".itemNumberField").classList.toggle("hidden",unknown||!item);
     box.querySelector(".itemNameField").classList.toggle("hidden",unknown||!item);
     box.querySelector(".valueField").classList.toggle("hidden",unknown||item);
     box.querySelector(".obtainedField").classList.toggle("hidden",unknown);
   }
   know.onchange=refresh;typ.onchange=refresh;refresh();
 });
 document.querySelectorAll(".removeOutcome").forEach(b=>b.onclick=()=>{b.closest(".outcome-box").remove();renumberOutcomes()});
}
function renumberOutcomes(){document.querySelectorAll(".outcome-box").forEach((b,i)=>{b.dataset.outcome=i;b.querySelector(".outcome-head strong").textContent=`Outcome ${i+1}`});wireOutcomeBoxes()}
function openDiscovery(action="Look"){
 let loc=detail?.kind==="location"?detail.id:state.current;
 modal(`<h2>Add action / discovery</h2><div class="form-grid">
 <label class="field">Location<input id="dLoc" type="number" value="${loc||""}"></label>
 <label class="field">Action<select id="dAction">${["Look","Help","Engage","Take","Overpower","Move"].map(x=>`<option ${x===action?"selected":""}>${x}</option>`).join("")}</select></label>
 <label class="field full">Specific action / interaction<input id="dSpecific" placeholder="e.g. Open treasure chest"></label>
 <label class="field full">Test details <span class="meta">(optional)</span><input id="dTest" placeholder="Record only what you know from the game"></label>
 </div><h3 style="margin-top:18px">Possible outcomes</h3><p class="meta">Record only outcomes the game has revealed. If you know another option exists but not what it gives, mark it Unknown.</p>
 <div id="outcomes">${outcomeBlock(0)}</div><button type="button" class="secondary" id="addOutcome">+ Add another outcome</button>
 <label class="field full" style="margin-top:15px">Notes<textarea id="dNotes" rows="3" placeholder="Anything else worth remembering"></textarea></label>
 <div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="saveDiscovery">Save discovery</button></div>`);
 wireOutcomeBoxes();
 $("addOutcome").onclick=()=>{let n=document.querySelectorAll(".outcome-box").length;$("outcomes").insertAdjacentHTML("beforeend",outcomeBlock(n));wireOutcomeBoxes()};
 $("cancel").onclick=close;
 $("saveDiscovery").onclick=async()=>{
   let loc=$("dLoc").value.trim();if(!loc)return;
   let outcomes=[...document.querySelectorAll(".outcome-box")].map(box=>{
     let knowledge=box.querySelector(".oKnowledge").value, rewardType=box.querySelector(".oType").value;
     return {condition:box.querySelector(".oCondition").value.trim(),knowledge,
       rewardType:knowledge==="known"?rewardType:"",
       itemNumber:knowledge==="known"&&rewardType==="Item"?box.querySelector(".oNumber").value.trim():"",
       itemName:knowledge==="known"&&rewardType==="Item"?box.querySelector(".oName").value.trim():"",
       value:knowledge==="known"&&rewardType!=="Item"?box.querySelector(".oValue").value.trim():"",
       obtained:knowledge==="known"?box.querySelector(".oObtained").checked:false};
   });
   if(!(await getDoc(doc(db,"expeditions",EID,"locations",loc))).exists())await setDoc(doc(db,"expeditions",EID,"locations",loc),{name:"",contents:"",notes:"",return:false,createdAt:serverTimestamp()});
   await addDoc(collection(db,"expeditions",EID,"discoveries"),{location:loc,action:$("dAction").value,specific:$("dSpecific").value.trim(),testDetails:$("dTest").value.trim(),outcomes,notes:$("dNotes").value.trim(),byUid:auth.currentUser.uid,byName:member.displayName,dateText:new Date().toLocaleDateString("en-AU",{day:"2-digit",month:"2-digit",year:"2-digit"}),createdAt:serverTimestamp(),schemaVersion:2});
   close();await load();render();
 }
}
function openMember(){modal(`<h2>Add Min</h2><p>Create Min in <strong>Firebase Authentication → Users</strong> first, then paste Min's User UID below.</p><div class="form-grid"><label class="field full">Min's User UID<input id="mUid" placeholder="Firebase User UID"></label></div><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="saveMember">Add Min</button></div>`);$("cancel").onclick=close;$("saveMember").onclick=async()=>{let uid=$("mUid").value.trim();if(!uid)return;await setDoc(doc(db,"expeditions",EID,"members",uid),{displayName:"Min",role:"member",joinedAt:serverTimestamp(),addedBy:auth.currentUser.uid});await load();close();render()}}
render();
